# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: D

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        dc:
          - dmd-latest
          - dmd-2.086.1
          - ldc-latest
        exclude:
          - { os: macOS-latest, dc: dmd-2.086.1 }

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: Checkout source
        uses: actions/checkout@v2

      - name: 'Build'
        run: |
          # Release build
          dub build --parallel -b release
          dub clean --all-packages -q
          # Run tests
      - name: 'Test with unit-threaded'
        if: matrix.dc != 'dmd-2.086.1' && runner.os != 'windows'
        run:
          dub test --root=tests/unit-threaded --parallel --coverage
      - name: 'Test with silly'
        if: matrix.dc != 'dmd-2.086.1'
        run:
          dub test --root=tests/silly --parallel --coverage
      - name: 'Test with d-unit'
        run:
          dub test --root=tests/d-unit --parallel
      - name: 'Tests with Trial'
        if: runner.os == 'Linux' && matrix.dc != 'dmd-2.086.1'
        run:
          dub run trial:runner@~master

      - name: Upload Coverage to Codecov
        # Upload test coverage
        if: github.ref == 'refs/heads/master' && runner.os == 'Linux' && matrix.dc == 'dmd-latest'
        run: bash <(curl -s https://codecov.io/bash)
